services:
  # Directus web service
  - type: web
    name: directus
    runtime: docker
    dockerfilePath: ./directus/Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      # Connection string to PostgreSQL provided by the Render database service
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: bebetter-db
          property: connectionString
      # Connection string to Redis/key‑value store (cache)
      - key: CACHE_CONNECTION_STRING
        fromService:
          type: keyvalue
          name: bebetter-cache
          property: connectionString
      # Admin credentials you set in Render Secrets
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      # Public base URL of your Directus instance
      - key: PUBLIC_URL
        sync: false
      # Disable Directus telemetry
      - key: DIRECTUS_TELEMETRY
        value: "false"

  # Background worker to run flows and other tasks
  - type: worker
    name: directus-worker
    runtime: docker
    dockerfilePath: ./directus/Dockerfile
    plan: starter
    autoDeploy: true
    startCommand: node worker.js
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: bebetter-db
          property: connectionString
      - key: CACHE_CONNECTION_STRING
        fromService:
          type: keyvalue
          name: bebetter-cache
          property: connectionString
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PUBLIC_URL
        sync: false

  # Cron job to run nightly housekeeping at 02:00 UTC
  - type: cron
    name: nightly-housekeeping
    runtime: python
    schedule: "0 2 * * *"
    buildCommand: "true"  # no build needed
    startCommand: |
      curl -X POST "$PUBLIC_URL/flows/nightly_housekeeping/run" -H "Authorization: Bearer $ADMIN_TOKEN" || true
    envVars:
      - key: PUBLIC_URL
        sync: false
      - key: ADMIN_TOKEN
        sync: false

  # Redis-like key-value store (cache)
  - type: keyvalue
    name: bebetter-cache
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: all

databases:
  # PostgreSQL database for Directus
  - name: bebetter-db
    plan: starter
