services:
  - type: web
    name: directus
    runtime: docker
    dockerfilePath: ./directus/Dockerfile
    plan: free            # Use Render’s free web service
    envVars:
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: bebetter-db
          property: connectionString
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: DIRECTUS_TELEMETRY
        value: "false"

databases:
  - name: bebetter-db
    plan: free            # Use Render’s free Postgres
