name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
      - name: Install dependencies
        working-directory: ./bebetter/mobile
        run: flutter pub get
      - name: Analyze
        working-directory: ./bebetter/mobile
        run: flutter analyze --no-fatal-infos
      - name: Run tests
        working-directory: ./bebetter/mobile
        run: flutter test --coverage