name: bebetter
description: Production‑ready scaffold for BeBetter
publish_to: "none" # This is a private package.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.3
  dio: ^5.3.3
  drift: ^2.6.0
  drift_sqflite: ^2.1.0
  sqlite3_flutter_libs: ^0.5.18
  flutter_local_notifications: ^15.1.0
  firebase_messaging: ^14.7.4
  video_player: ^2.7.2
  youtube_player_iframe: ^2.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/